# Generated by Django 5.0.6 on 2024-06-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_enterprise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enterprise',
        ),
        migrations.AddField(
            model_name='client',
            name='banner',
            field=models.ImageField(blank=True, default='aaa.png', upload_to=''),
        ),
    ]
