# Generated by Django 5.0.6 on 2024-07-10 20:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orm', '0009_alter_client_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badany_obiekt', models.CharField(choices=[('wegiel', 'Węgiel'), ('koks', 'Koks'), ('biomasa', 'Biomasa')], max_length=10)),
                ('opis', models.TextField()),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.client')),
            ],
        ),
    ]
